---
#
# Install Tripleo packages and undercloud.conf
#

- name: Setup mccloud/tripleo directories
  file:
    path: "{{item}}"
    state: directory
    owner: stack
    group: stack
  with_items:
    - /home/stack/images
    - /home/stack/templates
    - /home/stack/templates/firstboot
    - /home/stack/templates/pin
    - /home/stack/mccloud
    - /home/stack/mccloud/log
    - "{{log_dir}}"

- name: Install tripleo
  yum:
    name: python-tripleoclient

- name: Install ceph-ansible
  yum:
    name: ceph-ansible
  when: version >= 12

- name: Copy undercloud.conf
  template:
    src: undercloud.{{version}}.conf.j2
    dest: /home/stack/undercloud.conf
    owner: stack
    group: stack

- name: Copy containers-prepare-parameter
  template:
    src: containers-prepare-parameter.yaml.j2
    dest: /home/stack/containers-prepare-parameter.yaml
    owner: stack
    group: stack
  when: version >= 14
